### PR TITLE
Wip 1982 zone transfers

### PR DESCRIPTION
**Pull request by Jooty**
**Hello, nerds. This is your friendly reminder that Imlight's data sensitivity has become a lot more critical. Please do not share the `serverdata` database file, nor upload it to _any_ online location that you don't have full privacy over.**

We look pretty strong on this. Keeping this branch up for:
- Adding an aplenty amount of zone transfers.
- Bug fixes. Time for QA?

Keep in mind that for now the `serverdata` database is being rolled out with git and won't be ignored. Just be careful.

## ZoneTransferBuilder
Along with this branch comes our first Imlight specific tooling, dubbed the `ZoneTransferBuilder`. The only prerequisite for running this piece is the `AccessPass.xml` from the `Root.wad`. Everything else is downloaded directly from the patch server. If you want to update the current `serverdata` database, you may also place that in the `/input` directory of the build.

Coinciding are debug logs on Imlight to write what triggers are currently being activated. These triggers have the same names as in the tool, so in case you find an nondescript trigger name, the least you'll do is be able to find it's location.

### CODE REVIEW

**Comment by Phill030** [comment]
😱😎🤭😳

**Comment by gmrush** [comment]
😻😻😻😻

**Review by gmrush — APPROVED** [review]
LGTM, jooty is the goat

**Review by Phill030 — APPROVED** [review]
Good soup 🤓😘

**Comment by Jooty** [comment]
Branch will remain awake for any future zone transfers to be made.

**Pull request merged**
